package com.redhat.consulting.vertx;

/**
 * Class to centralize some constatns and enum types
 * @author dsancho
 *
 */
public class Constants {

	
	public static final String DEVICE_ACTION_EVENTS_ADDRESS = "device-action";
	public static final String DEVICE_REGISTRATION_EVENTS_ADDRESS = "device-reg";
	public static final String DEVICE_DATA_EVENTS_ADDRESS = "device-data";
	public static final String AMBIANCE_DATA_EVENTS_ADDRESS = "ambiance-data";

	public static final String DEVICE_ACTION_INCREASE_TEMPERATURE = "increase-temp";
	public static final String DEVICE_ACTION_DECREASE_TEMPERATURE = "decrease-temp";
	public static final String DEVICE_ACTION_DEACTIVATE = "increase-temp";
	
	public static final String DEVICE_ACTION_HEADER = "action";

	
	public static final String DEVICES_MAP = "DEVICES_MAP";
    public static final String DEVICES_ID_SEPARATOR = "-";
	

	public enum DeviceType {
		AIRCON;
	}
	
	public enum DeviceState {
		ON,
		OFF;
	}
	
	public enum DeviceAction {
		INCREASING,
		DECREASING,
		TURNOFF,
		NONE;
	}
	
	public enum DevicesPurpose {
		ACTIONABLE,
		REGISTERED;
	}
	
//	public enum DEVICE_MANAGEMENT_ACTION {
//		ACTIVATE_DEVICE,
//		TURNOFF_DEVICE;
//	}
	
	/* Errors Generated by unpredictable Vert.X behavior */
	public enum ErrorCode {
		DEVICE_MANAGEMENT_GET_DEVICE_ERROR(500),
		DEVICE_MANAGEMENT_GET_DEVICES_MAP_ERROR(501),
		DEVICE_MANAGEMENT_ACTIONS_BAD_ACTION (502);
		
		ErrorCode(int errorCode){
			this.errorCode = errorCode;
		}
		
		private int errorCode;
		
		public int getErrorCode(){
			return errorCode;
		}
	}
	
	/* Errors Generated by application erroneous behavior */
	public enum AppErrorCode {
		NON_REGISTERED_DEVICE(400),
		MESSAGE_OUT_OF_SYNC(401),
		DEVICE_UPDATE_NOT_POSSIBLE(402),
		MESSAGE_IS_EMPTY(403),
		DEVICE_ALREADY_REGISTERED(404);
		
		AppErrorCode(int errorCode){
			this.errorCode = errorCode;
		}
		
		private int errorCode;
		
		public int getErrorCode(){
			return errorCode;
		}
	}
}
