package com.redhat.consulting.vertx;

/**
 * Class to centralize some constatns and enum types
 * @author dsancho
 *
 */
public class Constants {

	public static final String HOMEPLANS_EVENTS_ADDRESS = "homeplans";
	
	public static final String AMBIANBCE_DATA_ADDRESS = "ambiance-data";
	
	public static final String DEVICE_ACTION_EVENTS_ADDRESS = "device-action";
	
	public static final String DEVICE_ACTION_HEADER = "action";

	public enum DeviceAction {
		INCREASING,
		DECREASING,
		TURNOFF}
	
	/* Errors Generated by unpredictable Vert.X behavior */
	public enum AppErrorCode {
		HOMEPLAN_REGULATOR_FAIL_RETRIEVE_HOMEPLAN(400),
		HOMEPLAN_REGULATOR_FAIL_APPLY_HOMEPLAN(401);

		AppErrorCode(int errorCode){
			this.errorCode = errorCode;
		}
		
		private int errorCode;
		
		public int getErrorCode(){
			return errorCode;
		}
	}
}
